spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fintech
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379
  flyway:
    enabled: true

security:
  jwt:
    issuer: fintech-api
    expiration-seconds: 3600
    # Set an environment variable named SECURITY_JWT_SECRET with a strong secret value
    secret: ${SECURITY_JWT_SECRET}

springdoc:
  swagger-ui:
    path: /swagger-ui.html

server:
  port: 8080

