spring.application.name=fintech-api
# spring.datasource.url=jdbc:postgresql://localhost:8080/fintech_db
# spring.datasource.username=
# spring.datasource.password=
# spring.datasource.driver-class-name=org.postgresql.Driver