spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fintech
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379

app:
  jwt:
    secret: change-this-secret-key-change-this-secret-key
    expiration-ms: 3600000

springdoc:
  swagger-ui:
    path: /swagger-ui.html

server:
  port: 8080
